### ISSUE TITLE
Builds 93, 94 broken - no checksum?

### ISSUE THREAD

**Issue by jacksongoode** [ungoogled-software/ungoogled-chromium-fedora#14]
I was just checking to see if this repo was getting updated as there were no new builds since 92 for me on Fedora 34. It looks like there are some build issues from OBS across a number of arches.

**Comment by wchen342** [comment]
cr93 was in testing repo but I didn't push to stable repo because there was a problem with CentOS I cannot solve. You can get v93 from [here](https://build.opensuse.org/package/binaries/home:ungoogled_chromium:testing/ungoogled-chromium-fedora/Fedora_34).
I will push v94 soon since CentOS 8 seems to be fixed.

**Comment by wchen342** [comment]
v94 is on OBS now: https://build.opensuse.org/package/binaries/home:ungoogled_chromium/ungoogled-chromium-fedora/Fedora_34
